apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.websecure.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
    - {{ .Values.ingress.websecure.secretName }}
  secretName: {{ .Values.ingress.websecure.secretName }}
  issuerRef:
    name: letsencrypt-prod #staging # Use the issuer created previously
    kind: ClusterIssuer