apiVersion: v1
kind: Service
metadata:
  name: {{ include "Sprinkler.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "Sprinkler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: sprinkler
  externalName: {{ .Values.service.externalName }}
  selector:
    {{- include "Sprinkler.selectorLabels" . | nindent 4 }}
