--- 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sprinkler-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "Sprinkler.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - kind: {{ .Values.ingress.web.kind }}
      match: {{ .Values.ingress.web.match}}
      middlewares:
        - name: redirect-https
      services:
        - name: {{ include "HomeAssistant.fullname" . }}
          port: {{ .Values.ingress.web.serviceport }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sprinkler-websecure
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "Sprinkler.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: {{ .Values.ingress.websecure.kind }}
      match: {{ .Values.ingress.websecure.match }}
      services:
        - name:  {{ include "HomeAssistant.fullname" . }}
          port: {{ .Values.ingress.websecure.serviceport}}
  tls:
    secretName: {{ .Values.ingress.websecure.secretName }}  
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: {{ .Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true