apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
