{{- range $.Values.pubsubs}}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  #temp
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: {{ .host }}
    - name: redisPassword
      secretKeyRef:
        name: redis
        key: redis-password
---        
{{- end }}
