
# Create the load balancing service
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-scheduler.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "helm-scheduler.name" . }}
    chart: {{ template "helm-scheduler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}