apiVersion: v1
kind: Service
metadata:
  name: {{ include "SchedulerService.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "SchedulerService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tcp8080
  selector:
    {{- include "SchedulerService.selectorLabels" . | nindent 4 }}
