namespace: ai

fullnameOverride: ai-schedulerservice

replicaCount: 1

image:
  repository: neichmann/schedulerservice
  tag: latest
  pullPolicy: IfNotPresent


containerPort: 8080


service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080