apiVersion: v1
kind: Service
metadata:
  name: {{ include "DataExporter.fullname" . }}
  labels:
    {{- include "DataExporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: TCP-5000
  selector:
    {{- include "DataExporter.selectorLabels" . | nindent 4 }}
