apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pythonaitrainer-env
data:
  APP_CHANNEL_ADDRESS: ""
  APP_PORT: "5000"
  DAPR_HTTP_PORT: "3520"
  DAPR_METRICS_PORT: "57828"
  APP_ID: "pythonaitrainer"
