apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-python-data
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: longhorn-test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-python-results
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: longhorn-test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
