apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-python-data
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
